server:
  port: 8000
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
    session:
      timeout: 2h

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update


  thymeleaf:
    cache: false
    mode: HTML

#需要设置processDefinitionLocationSuffixes，不然form_key找不到form文件
  activiti:
    processDefinitionLocationSuffixes[0]: "**.bpmn20.xml"
    processDefinitionLocationSuffixes[1]: "**.bpmn"
    processDefinitionLocationSuffixes[2]: "**.form"

wechat:
  cp:
    corpId: ww14ab63a72288b185
    agentId: 1000026
    secret: rqL9FZDTiLmt-srhTN1oKet6isdO-Y9jgWDvqZK9PEo
    token: 111
    aesKey: 111

logging:
  file: logs/oa.log
  level:
    root: INFO