server:
  port: 8000
  servlet:
    session:
      timeout: 1m

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update

  thymeleaf:
    cache: false
    mode: HTML

  activiti:
    processDefinitionLocationSuffixes[0]: "**.bpmn20.xml"
    processDefinitionLocationSuffixes[1]: "**.bpmn"
    processDefinitionLocationSuffixes[2]: "**.form"

wechat:
  cp:
    corpId: ww14ab63a72288b185
    agentId: 1000026
    secret: rqL9FZDTiLmt-srhTN1oKet6isdO-Y9jgWDvqZK9PEo
    token: 111
    aesKey: 111