server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update

  thymeleaf:
    cache: false
    mode: HTML

wechat:
  cp:
    corpId: ww14ab63a72288b185
    appConfigs:
      - agentId: 1000001
        secret: 1111
        token: 111
        aesKey: 111
      - agentId: 1000002
        secret: 1111
        token: 111
        aesKey: 111
